package yuma140902.lepton;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraftforge.oredict.OreDictionary;
import yuma140902.lepton.config.ModConfigCore;
import yuma140902.lepton.proxy.CommonProxy;
import yuma140902.lepton.recipes.Recipes;
import yuma140902.lepton.util.LeptonProperties;

@Mod(modid = ModLepton.MOD_ID, name = ModLepton.MOD_NAME, version = ModLepton.MOD_VERSION, useMetadata = true, guiFactory = LeptonProperties.MOD_CONFIG_GUI_FACTORY)
public class ModLepton {
	
	@Mod.Metadata
	public static ModMetadata modMetadata;
	
	@Mod.Instance
	public static ModLepton INSTANCE;
	
	@SidedProxy(clientSide = LeptonProperties.PROXY_CLIENT, serverSide = LeptonProperties.PROXY_SERVER)
	public static CommonProxy proxy;
	
	public static final String MOD_ID = "lepton";
	public static final String MOD_NAME = "Lepton";
	public static final String MOD_TEXTURE_DOMAIN = "lepton";
	public static final String MOD_UNLOCALIZED_ENTRY_DOMAIN = "lepton";
	public static final String MINECRAFT_VERSION = "1.7.10";
	public static final String MOD_VERSION = "0.0.0";
	public static final Logger LOGGER = LogManager.getLogger(MOD_NAME);
	
	
	private void loadModMetadata(ModMetadata modMetadata) {
		modMetadata.modId = MOD_ID;
		modMetadata.name = MOD_NAME;
		modMetadata.version = MOD_VERSION;
		modMetadata.authorList.add("yuma140902");
		modMetadata.description = "Tweak Minecraft 1.7.10. Inspired from Quark by vaskii";
		modMetadata.credits = "Quark by vaskii ... A Great Minecraft tweaking mod";
//		modMetadata.url = "https://minecraft.curseforge.com/projects/uptodatemod";
		modMetadata.autogenerated = false;
	}
	
	private void tweakVanilla() {
		
		for(int meta = 0; meta < 16; ++meta) {
			OreDictionary.registerOre(LeptonProperties.OREDICT_WOOL, new ItemStack(Blocks.wool, 0, meta));
		}
		
		final int stacksizeMinecarts = ModConfigCore.Props.stackableItemsMinecarts.getInt();
		Items.minecart.setMaxStackSize(stacksizeMinecarts);
		Items.chest_minecart.setMaxStackSize(stacksizeMinecarts);
		Items.command_block_minecart.setMaxStackSize(stacksizeMinecarts);
		Items.furnace_minecart.setMaxStackSize(stacksizeMinecarts);
		Items.hopper_minecart.setMaxStackSize(stacksizeMinecarts);
		Items.tnt_minecart.setMaxStackSize(stacksizeMinecarts);
		
		final int stacksizeSaddles = ModConfigCore.Props.stackableItemsSaddles.getInt();
		Items.saddle.setMaxStackSize(stacksizeSaddles);
		
		final int stacksizeStew = ModConfigCore.Props.stackableItemsStew.getInt();
		Items.mushroom_stew.setMaxStackSize(stacksizeStew);
		
		final int stacksizeBucket = ModConfigCore.Props.stackableItemsBucket.getInt();
		Items.bucket.setMaxStackSize(stacksizeBucket);
//		Items.lava_bucket.setMaxStackSize(stacksizeBucket);
//		Items.milk_bucket.setMaxStackSize(stacksizeBucket);
//		Items.water_bucket.setMaxStackSize(stacksizeBucket);
	}
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		loadModMetadata(modMetadata);
		ModConfigCore.loadConfig(event);
		LOGGER.info("preInit");
		
		tweakVanilla();
	}
	
	@EventHandler
	public void init(FMLInitializationEvent event) {
		LOGGER.info("init");
		
		Recipes.register();
		
		proxy.registerEventHandlers();
	}
	
	@EventHandler
	public void postInit(FMLPostInitializationEvent event) {
		LOGGER.info("postInit");
	}
}
